// Copyright (c) 2026, Saad and contributors
// For license information, please see license.txt

frappe.dom.set_style(`
  .dt-cell--col-0 { min-width: 55px !important; width: 55px !important; }
  .dt-cell--col-0 .dt-cell__content { overflow: visible !important; }
`);

frappe.query_reports["Catalog Modern Grid"] = {
	filters: [
		{ fieldname: "company", label: __("Company"), fieldtype: "Link", options: "Company", reqd: 1,
			on_change: function () {
				frappe.query_report.set_filter_value("item_group", "");
				frappe.query_report.set_filter_value("category", "");
				frappe.query_report.set_filter_value("subcategory", "");
			}
		},
		{ fieldname: "price_list", label: __("Price List"), fieldtype: "Link", options: "Price List", reqd: 1 },
		{ fieldname: "item_group", label: __("Product Type"), fieldtype: "Link", options: "Item Group",
			get_query: function () {
				var company = frappe.query_report.get_filter_value("company");
				var price_list = frappe.query_report.get_filter_value("price_list");
				return {
					query: "cotton_valley.cotton_valley.report.catalog_modern_grid.catalog_modern_grid.get_product_types",
					filters: { company: company || "", price_list: price_list || "" }
				};
			}
		},
		{ fieldname: "category", label: __("Category"), fieldtype: "Link", options: "Product Category",
			get_query: function () {
				var company = frappe.query_report.get_filter_value("company");
				return { filters: company ? { company: company } : {} };
			}
		},
		{ fieldname: "subcategory", label: __("Sub-Category"), fieldtype: "Link", options: "Product Subcategory",
			get_query: function () {
				var company = frappe.query_report.get_filter_value("company");
				var category = frappe.query_report.get_filter_value("category");
				return {
					query: "cotton_valley.cotton_valley.report.catalog_modern_grid.catalog_modern_grid.get_subcategories",
					filters: { company: company || "", category: category || "" }
				};
			}
		},
		{ fieldname: "hide_price", label: __("Hide Price in PDF"), fieldtype: "Check", default: 0 },
		{
			fieldname: "sort",
			label: __("Sort"),
			fieldtype: "Select",
			options: [
				"",
				"Ascending Order",
				"Descending Order",
				"Low-High Price",
				"High-Low Price",
				"A-Z Order",
				"Z-A Order"
			].join("\n"),
			default: ""
		}
	],

	onload: function (report) {
		report.page.add_inner_button(__("Download PDF"), function () {
			const current = report.get_values();
			const product_count = (frappe.query_report.data || []).length;
			let d = new frappe.ui.Dialog({
				title: __("Download Product Catalog PDF"),
				fields: [
					{ fieldname: "header_title", fieldtype: "Data", label: __("Header Title"), default: (current.header_title || "PRODUCT CATALOG") },
					{ fieldname: "header_sub", fieldtype: "Data", label: __("Header Subtitle"), description: __("Shown below the title in the PDF"), default: (current.header_sub || `Total Products: ${product_count}`) },
					{ fieldname: "column_break_1", fieldtype: "Column Break" },
					{ fieldname: "prepared_by", fieldtype: "Data", label: __("Prepared By"), default: (current.prepared_by || frappe.session.user_fullname) },
					{ fieldname: "prepared_for", fieldtype: "Link", options: "Customer", label: __("Prepared For"), reqd: 1, description: __("Buyer / customer name shown in the header"), default: (current.prepared_for || "") },
					{ fieldname: "footer_note", fieldtype: "Data", label: __("Footer Custom Text"), description: __("e.g. 'Generated by UniCott Sales'"), default: (current.footer_note || "") },
					{ fieldname: "hide_price", fieldtype: "Check", label: __("Hide Price in PDF"), default: (current.hide_price || 0) },
				],
				primary_action_label: __("Download"),
				primary_action: function (values) {
					d.hide();
					const filters = report.get_values();
					filters.header_title = values.header_title || "PRODUCT CATALOG";
					filters.header_sub = values.header_sub || "";
					filters.prepared_by = values.prepared_by || "";
					filters.prepared_for = values.prepared_for || "";
					if (values.footer_note) filters.footer_note = values.footer_note;
					filters.hide_price = values.hide_price ? 1 : 0;
					const args = encodeURIComponent(JSON.stringify(filters));
					const url = `/api/method/cotton_valley.cotton_valley.report.catalog_modern_grid.catalog_modern_grid.download_catalog_modern_grid_pdf?filters=${args}`;
					window.open(url, "_blank");
				}
			});
			d.show();
		}).addClass("btn-primary");
	}
};
